"""request_id"""
from enum import IntEnum

class WebsocktRequestId(IntEnum):
    """WebsocktRequestId"""
    QUERY_PRINTER_OBJECTS = 0
    SUBSCRIBE_REQUEST = 1
    QUERY_SERVER_INFO = 2
    ADJUST_ZOFFSET = 3
    WRITE_SPEED_FACTOR = 4
    EXTRUDE_FILAMENT_CMD = 5
    PERFORM_MOVE_CMD = 6
    TURN_MOTORS_OFF_CMD = 7
    LED_CMD = 8
    SET_FAN_SPEED_CMD = 9
    SET_HEATER_TEMPERATURE_CMD = 10
    UNSUBSCRIBE_PRINTER_OBJECTS = 11
    QUERY_PRINTER_INFO = 12
    FIRMWARE_RESTART = 13
    RESTART = 14
    PERFORM_Z_TILT = 15
    SET_USER_POS = 16
    PRINT_PAUSE = 17
    PRINT_RESUME = 18
    PRINT_CANCEL = 19
